[package]
name = "non-deterministic-minesweeper"
version = "0.1.0"
authors = ["Lucas Clemente Vella <lvella@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.8.4"
iced = "0.3"
itertools = "0.10.1"

[profile.release]
lto = "thin"
